### ISSUE TITLE
doxygen/breathe: need-role throws error

### ISSUE THREAD

**Issue by danwos** [useblocks/sphinxcontrib-needs#231]
Follow-up of #193

A :need: role within doxygen throws the following exception. This time from Breathe however.

```
Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/docutils-0.16-py3.9.egg/docutils/nodes.py", line 2018, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'breathe.renderer.sphinxrenderer.NodeFinder'> visiting unknown node type: NeedRef

```

**Comment by danwos** [comment]
Fixed by PR #233

**Comment by twodrops** [comment]
@danwos This still does not work for me :( Also @sembooooo reported this to me.
Strange that it works for you [here](https://sphinx-scale.readthedocs.io/en/latest/demos/index.html#needs_doxygen_breathe). Can you please check with the current "master" version again?

Exception is
```
Exception occurred:
  File "/usr/local/lib/python3.9/site-packages/docutils/nodes.py", line 2018, in unknown_visit
    raise NotImplementedError(
NotImplementedError: <class 'breathe.renderer.sphinxrenderer.NodeFinder'> visiting unknown node type: NeedRef
```

**Comment by danwos** [comment]
I unable to  reproduce this error :/

I recognized that breathe did not support Sphinx 4.0 in versions some weeks ago.
So this maybe lead to a downgrade of the sphinx-needs version.
Can you please recheck, that Sphinx and Sphinx-needs are installed with the newest version.

Maybe you could also check, if your setup works with the demo from sphinx-scale.
https://github.com/useblocks/sphinx-scale/tree/main/demos/needs_doxygen_breathe
It is a standalone sphinx-project. So a ``make html`` in the above folder should directly work.

This test is important for me to know, if the error is based on version-conflicts or if you have a case, which my tests do not cover yet and I have to understand it even more :)

Here a list of versions I have used.
```
breathe==4.30.0
docutils==0.17.1
Sphinx==4.0.0
sphinx-copybutton==0.3.3
sphinxcontrib-needs==0.6.2
sphinxcontrib-plantuml==0.21
``

Thanks for your support.

**Comment by twodrops** [comment]
@danwos 

I have the same versions as you except for docutils
```
breathe==4.30.0
docutils==0.16
Sphinx==4.0.0
sphinx-copybutton==0.3.3
sphinxcontrib-needs==0.6.2
sphinxcontrib-plantuml==0.21
```

`docutils==0.17.1` is somehow incompatible with `sphinx_rtd_theme=0.5.2`. But now I uninstalled sphinx_rtd_theme and upgraded to `docutils==0.17.1`, but still the problem exists.

I will test with your example above and give feedback.

**Comment by danwos** [comment]
Looks like the problem is in breathe.

A comment like this works:
```
/** 
 *
 * /rst
 * .. req:: test me
 *   :id: test_01
 * 
 * Ref example  -> :need:`test_01`
 * /endrst
```
This not:
```
```
/** 
@rst
.. req:: test me
   :id: test_01
Ref example  -> :need:`test_01`
@endrst
```
If the last one is used, Breathe complains about an unknown node "NeedRef", which gets normally resolved/replaced by Sphinx-Needs before Breathe should interpret it.

**Comment by danwos** [comment]
Mhh maybe it only works, because I forgot to activate asterisk handling like ``\verbatim embed:rst:leading-asterisk``
and may example does not contain complex rst data, like a list.
See https://breathe.readthedocs.io/en/latest/markups.html#handling-leading-asterisks

Have to make further tests....

**Comment by danwos** [comment]
No, everything is working.
A file like this gets rendered well:
```
/**
 * \file
 *
 * \brief This file does not even exist in the real world.
 *
 * \rst
 * .. note:: An example hpp to show doxygen problem
 *
 * .. need:: Need inside hpp
 *    :id: NEED_2
 *    :status: open
 *    :links: NEED_1
 *
 *    Unique content string to easily identify in generated xml files: FOOBAR2021
 *
 * Link test to :need:`NEED_1`
 *
 * List example
 *
 * * point 1
 * * point 2
 *
 * \endrst
 */

namespace example
{
namespace doxygen
{
} // namespace doxygen
} // namespace example


```

**Comment by danwos** [comment]
Okay, the cause of the problem is not the format.

But it looks like that the directives ``doxygenfile`` and ``doxygenclass`` are handled differently.
I get not error with ``doxygenfile``, although it documents the included class as well.
But ``doxygenclass`` throws an exception, when it tries to document the same class.

**Comment by danwos** [comment]
Forgot to mention the created breathe issue: https://github.com/michaeljones/breathe/issues/713

**Comment by maxlutz98** [comment]
FYI: I raised this issue for breathe, too. I didn't see that it is already raised.
Raised issue: michaeljones/breathe#807
My issue got already resolved. I still wait for a new breathe release to verifiy this.
